### ISSUE TITLE
Spammer's dream

### ISSUE THREAD

**Issue by Plazmaz** [distributedweaknessfiling/DWF-Legal-Acceptance#1]
Hey, it would be nice to change https://github.com/distributedweaknessfiling/DWF-Legal-Acceptance/tree/master/Terms-Of-Use not to directly link the email address. Otherwise this creates a nice, convenient list for web scrapers to use.

**Comment by kurtseifried** [comment]
Pretty sure keeping email addresses secret doesn't work anymore. If you can't have a public address then I suggest you setup a different account to use with respect to DWF interaction. Thanks!

**Comment by Plazmaz** [comment]
@kurtseifried yep, fair enough. I suppose this is a required field for CVEs anyways.
